/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Tue Jun  7 08:06:57 2011
 */
#ifndef __CEXTRACT__
#if __STDC__

k3FreqMemInfo * newK3FreqMemInfo ( void );
int checksum ( char asciiHex[], int from, int to, char * checksumAscii );
void spaceHexString ( char * hexStr, int interval );
static void parseResponse ( char * erCmd );
static int freqA ( void );
static int freqB ( void );
/*static int calcFreq ( char fStr[], char xvtrFlags );*/
int calcFreq ( k3VfoFreq f, char xvtrFlags );
static char * getLabel ( void );
static int bandIndexToFreq ( int bandNum );
static char decodeChar ( unsigned int c );
static char * modeA ( void );
static char * modeB ( void );
static char * mode ( char modeChar, char altChar, char flags7, char fmInfo, char dataMode );
static int repeaterOffset ( void );
static int repeaterOffsetStr ( char * rptrOffset );
static int isModeCw ( void );
static int isModeLsb ( void );
static int isModeUsb ( void );
static int isModeData ( void );
static int isModeAm ( void );
static int isModeFm ( void );
static int modeAlt ( void );
static int nbOn ( void );
static int ant ( void );
static int preampOn ( void );
static int attOn ( void );
static int rxAntOn ( void );
static int splitOn ( void );
static int nrOn ( void );
static float plTone ( void );
static float plToneStr ( char * plHex );
static unsigned char stox ( unsigned char byte );
static void printBrief ( void );
static void printRaw ( void );
static void printVerbose ( void );

#else /* __STDC__ */

k3FreqMemInfo * newK3FreqMemInfo (/* void */);
int checksum (/* char asciiHex[], int from, int to, char * checksumAscii */);
void spaceHexString (/* char * hexStr, int interval */);
static void parseResponse (/* char * erCmd */);
static int freqA (/* void */);
static int freqB (/* void */);
static int calcFreq (/* char fStr[], char xvtrFlags */);
static char * getLabel (/* void */);
static int bandIndexToFreq (/* int bandNum */);
static char decodeChar (/* unsigned int c */);
static char * modeA (/* void */);
static char * modeB (/* void */);
static char * mode (/* char modeChar, char altChar, char flags7, char fmInfo, char dataMode */);
static int repeaterOffset (/* void */);
static int repeaterOffsetStr (/* char * rptrOffset */);
static int isModeCw (/* void */);
static int isModeLsb (/* void */);
static int isModeUsb (/* void */);
static int isModeData (/* void */);
static int isModeAm (/* void */);
static int isModeFm (/* void */);
static int modeAlt (/* void */);
static int nbOn (/* void */);
static int ant (/* void */);
static int preampOn (/* void */);
static int attOn (/* void */);
static int rxAntOn (/* void */);
static int splitOn (/* void */);
static int nrOn (/* void */);
static float plTone (/* void */);
static float plToneStr (/* char * plHex */);
static unsigned char stox (/* unsigned char byte */);
static void printBrief (/* void */);
static void printRaw (/* void */);
static void printVerbose (/* void */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
