/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 *
 *   Created: Fri Jun  3 20:10:45 2011
 */
#ifndef __CEXTRACT__
#if __STDC__

extern int openPort ( char *device );
extern void configurePort ( int portFd, int speed );
extern int abSwap ( int fd );
extern int getKeyerSpeed ( int fd );
extern void setKeyerSpeed ( int fd, int speed );
extern void waitWhileBusy ( int fd );
extern void sendCW ( int fd, char *text );
extern void setExtendedMode ( int fd );
extern void setK2ExtendedMode ( int fd );
extern int getFreq ( int fd, char vfo );
extern void setFreq ( int fd, char vfo, int hz );
extern void quitCw ( int fd );
extern int setMemChannel ( int fd, int memNum );
extern int setMode ( int fd, int opMode );
extern int determineMode ( int hz );
extern void rate ( int fd );
extern double getPower ( int fd );
extern void setPower ( int fd, float watts );
extern int getPreamp ( int fd );
extern void setPreamp ( int fd, int on );
extern int getAttenuator ( int fd );
extern void setAttenuator ( int fd, int on );
extern void setSplit ( int fd, int hz, int hzUp );
extern void getDisplay ( int fd );
extern void tune ( int fd );
extern char * k3Command ( int fd, char * cmd, int msecSleep, int bytesToRead );

#else /* __STDC__ */

extern int openPort (/* void */);
extern void configurePort (/* int portFd */);
extern int abSwap (/* int fd */);
extern int getKeyerSpeed (/* int fd */);
extern void setKeyerSpeed (/* int fd, int speed */);
extern void waitWhileBusy (/* int fd */);
extern void sendCW (/* int fd, char *text */);
extern void setExtendedMode (/* int fd */);
extern void setK2ExtendedMode (/* int fd */);
extern int getFreq (/* int fd, char vfo */);
extern void setFreq (/* int fd, char vfo, int hz */);
extern void quitCw (/* int fd */);
extern int setMemChannel (/* int fd, int memNum */);
extern int setMode (/* int fd, int opMode */);
extern int determineMode (/* int hz */);
extern void rate (/* int fd */);
extern double getPower (/* int fd */);
extern void setPower (/* int fd, float watts */);
extern int getPreamp (/* int fd */);
extern void setPreamp (/* int fd, int on */);
extern int getAttenuator (/* int fd */);
extern void setAttenuator (/* int fd, int on */);
extern void setSplit (/* int fd, int hz, int hzUp */);
extern void getDisplay (/* int fd */);
extern void tune (/* int fd */);
extern char * k3Command (/* int fd, char * cmd, int msecSleep, int bytesToRead */);

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
